services:
  mongodb:
    image: mongo:4.4.29
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=characters

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/manu/Escritorio/Facultad/Desarrollo de Software/characters-api/src/character/migrations/script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=characters
volumes:
  mongodb_data:
    driver: local
  postgres_data:
    driver: local
